sudo: required

env:
  global:
  - REPO=bhavikkumar/init-aws-swarm
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: aNPQnqHhYTOP5LkROtZhfiv8RaXRtJu4PLP2Yhj62F0imf/pIqKz88aVLFcfmHKkNU7JeI4zUWqIJrZ1bQn/1UD4ZfJkOwHKgqPGnQZ5mQV/dHiDt1Xv0G7KqZxUE8Ufs0EEiYMfj13C6KXlLgYMXwKmNq6XZ5nyUYga9m4nnOb4I+RYw3GKyaGNoyMArZA2JskV7LxbZ92ZvG3W1bIb1Pwi111HP9720BjoPoeLNK5566uA+yZfEUkv/GTfs5BAwIdhXROi8LBLFxlqBGHqjLEcz9qNTrdJc/JzFI5e6Y+bYXhr1rBiI9ji2THvSp6PtAtHsjObRdoT3j+2EfCxEnuOcR0B+zAu7i33TXCMq/w7gBuMaq5bDMiTWd54YEp1u25K1Tija9l5EkWXJYgLlPuuggo4cdTgFbnX6DFpBazgyCgHjXJebvYs4liTzAP1+eTgY5Lz2voZxt/OLEeewOnFQLnANJk2B1JBoulH+W4cYQg1QBP5w7p0u8NhmXQAeYEa1Dpa2TwEoaO7kwc7oDNpBNR5DTrmdBz7oQh9PtBR85H28UeyK1FC4wJG0my5GWpYmOypHl3E+mtqomMT05I4hiZyaFhvhHOnHeJjpZhMWfKfoMp6DVqn8B9drtb6wRkx9BL220E5i6v0a/tEFT6iVKcadRHhBaaX9H8388Y=
  - secure: Q3eRuWRODywmg+EPF7dtzAXkqfXb8FbL1biXGMclZbIjX4nzE/mgi9u+y94SttKqqoEw11KSaii1ApX3rV+A++KRNMAS90zfdks4eGxxXfF+j/9SSDUHMgstscmWbn9dTcmnulDRAyJCvyH0uzv5l5i048EmkHiTFRuD4Bz1lb8GYtqD/A9P+CqJ3ErDQtuvvHXoOZW0V60QZ7RM/pM2hY9Y7oUdzixWlKiBKyDpF2hyf79E1HTkCulEm9k1mqt96xiIzkBapmXqQoTnFkZYoGy07ybm4H5LJ3uQMFlHGgoKc5y5YYaRlHz9hMqiBkRSTreEafinrWFU8kw5/egLO87aF+G+7HDLoN90zXsiQOWQaKKNsjj9nW4+/pszwOTxjSWsQ7AFOMuzbT8VlBPJaWege7Wis3jnt8pRMPloDVP07o3fLLdx8M0g9mttK3uciHXaH4g8IflqSeFhmZsGzKuLyyE3jIeIEaRkrBNzbkKNFHt7o8rlBopSVTreKxn0owkEB8ZfQaIW+Daq9Bq9yPm1MORCePmB4x8M5CuptXJxzfm1t5NzpWY1juz9t6gHGlJk4Am3c0R/W39yw9G/LBhBz+CNL9NBQXR08EaL8Kxh7xDKt1d50xRB1XAv6QWcGRATHBQlda/yh052fsj5rfVfR4sK3789HaEevXCF/3o=

services:
- docker

before_script:
- export TZ=Pacific/Auckland
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`

branches:
  only:
  - master

script:
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
  docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
